
import { Table } from "@/types/schema";

export const baseModulesSchema: Record<string, Table[]> = {
  // Module blog avec vraies tables/champs (exemple réaliste)
  blog: [
    {
      id: "posts",
      name: "posts",
      description: "Articles du blog (titre, contenu, catégorie, auteur, SEO, etc.)",
      fields: [
        {
          name: "id",
          type_general: "uuid",
          type_sql: "TEXT PRIMARY KEY",
          required: true,
          unique: true,
          primary_key: true,
          description: "ID unique (UUID) de l'article",
          example_value: "9fd0-...-zz",
          slug_compatible: false,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "title",
          type_general: "string",
          type_sql: "TEXT NOT NULL",
          required: true,
          unique: false,
          primary_key: false,
          description: "Titre de l'article",
          example_value: "10 conseils SEO",
          slug_compatible: true,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "content",
          type_general: "text",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Contenu HTML/Markdown de l'article",
          example_value: "Voici comment optimiser...",
          slug_compatible: false,
          acf_field_type: "textarea",
          ui_component: "textarea",
        },
        {
          name: "category_id",
          type_general: "relation",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Catégorie de l'article",
          example_value: "marketing",
          slug_compatible: false,
          acf_field_type: "select",
          ui_component: "relation-picker",
          foreign_key: "categories.id",
          relation_cardinality: "N-1",
        },
        {
          name: "author_id",
          type_general: "relation",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Auteur de l'article",
          example_value: "john_doe",
          slug_compatible: false,
          acf_field_type: "select",
          ui_component: "relation-picker",
          foreign_key: "users.id",
          relation_cardinality: "N-1",
        },
        {
          name: "date_created",
          type_general: "datetime",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Date de création de l'article",
          example_value: "2024-06-09T15:00:00Z",
          slug_compatible: false,
          acf_field_type: "datepicker",
          ui_component: "datepicker",
        },
        {
          name: "slug",
          type_general: "string",
          type_sql: "TEXT UNIQUE",
          required: true,
          unique: true,
          primary_key: false,
          description: "Slug unique pour URL",
          example_value: "10-conseils-seo",
          slug_compatible: true,
          acf_field_type: "text",
          ui_component: "input",
        },
      ],
    },
    {
      id: "categories",
      name: "categories",
      description: "Catégories des articles de blog.",
      fields: [
        {
          name: "id",
          type_general: "uuid",
          type_sql: "TEXT PRIMARY KEY",
          required: true,
          unique: true,
          primary_key: true,
          description: "ID unique catégorie",
          example_value: "875f-...",
          slug_compatible: false,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "name",
          type_general: "string",
          type_sql: "TEXT NOT NULL",
          required: true,
          unique: true,
          primary_key: false,
          description: "Nom de la catégorie",
          example_value: "Marketing",
          slug_compatible: true,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "description",
          type_general: "text",
          type_sql: "TEXT",
          required: false,
          unique: false,
          primary_key: false,
          description: "Description de la catégorie",
          example_value: "Toutes les astuces marketing...",
          slug_compatible: false,
          acf_field_type: "textarea",
          ui_component: "textarea",
        },
      ],
    },
    {
      id: "comments",
      name: "comments",
      description: "Commentaires sur les articles du blog.",
      fields: [
        {
          name: "id",
          type_general: "uuid",
          type_sql: "TEXT PRIMARY KEY",
          required: true,
          unique: true,
          primary_key: true,
          description: "ID unique du commentaire",
          example_value: "c-2121-...",
          slug_compatible: false,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "post_id",
          type_general: "relation",
          type_sql: "TEXT NOT NULL",
          required: true,
          unique: false,
          primary_key: false,
          description: "Article concerné",
          example_value: "9fd0...",
          slug_compatible: false,
          acf_field_type: "select",
          ui_component: "relation-picker",
          foreign_key: "posts.id",
          relation_cardinality: "N-1",
        },
        {
          name: "author_name",
          type_general: "string",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Auteur du commentaire",
          example_value: "Alice",
          slug_compatible: false,
          acf_field_type: "text",
          ui_component: "input",
        },
        {
          name: "content",
          type_general: "text",
          type_sql: "TEXT",
          required: true,
          unique: false,
          primary_key: false,
          description: "Texte du commentaire",
          example_value: "Très bon article !",
          slug_compatible: false,
          acf_field_type: "textarea",
          ui_component: "textarea",
        },
        {
          name: "date_posted",
          type_general: "datetime",
          type_sql: "TEXT NOT NULL",
          required: true,
          unique: false,
          primary_key: false,
          description: "Date/heure du commentaire",
          example_value: "2024-06-09T17:45:00Z",
          slug_compatible: false,
          acf_field_type: "datepicker",
          ui_component: "datepicker",
        },
      ],
    },
  ],
  // Tu peux continuer à ajouter ici d’autres modules (ecommerce, gallery…) au même format !
};
